/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AbstractEle: typeof import("./src/components/public/AbstractEle/index.vue")["default"];
    AppSearch: typeof import("./src/components/base/AppSearch/index.vue")["default"];
    ContextMenu: typeof import("./src/components/base/ContextMenu/index.vue")["default"];
    Describe: typeof import("./src/components/business/Index/Describe/index.vue")["default"];
    Dynamic: typeof import("./src/components/business/Dashboard/workbench/Dynamic/index.vue")["default"];
    EffectScatter: typeof import("./src/components/business/Dashboard/dataReport/EffectScatter/index.vue")["default"];
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElAvatar: typeof import("element-plus/es")["ElAvatar"];
    ElBadge: typeof import("element-plus/es")["ElBadge"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCard: typeof import("element-plus/es")["ElCard"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDivider: typeof import("element-plus/es")["ElDivider"];
    ElDrawer: typeof import("element-plus/es")["ElDrawer"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElFooter: typeof import("element-plus/es")["ElFooter"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElLink: typeof import("element-plus/es")["ElLink"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElPopover: typeof import("element-plus/es")["ElPopover"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    ElTableV2: typeof import("element-plus/es")["ElTableV2"];
    ElTabPane: typeof import("element-plus/es")["ElTabPane"];
    ElTabs: typeof import("element-plus/es")["ElTabs"];
    ElTag: typeof import("element-plus/es")["ElTag"];
    ForgetPassword: typeof import("./src/components/business/Login/ForgetPassword/index.vue")["default"];
    Form: typeof import("./src/components/business/Login/Form/index.vue")["default"];
    GLogo: typeof import("./src/components/base/GLogo/index.vue")["default"];
    GradientStackedArea: typeof import("./src/components/business/Dashboard/dataReport/GradientStackedArea/index.vue")["default"];
    HalfDoughnut: typeof import("./src/components/business/Dashboard/dataReport/HalfDoughnut/index.vue")["default"];
    Introduction: typeof import("./src/components/business/Index/Introduction/index.vue")["default"];
    Layout: typeof import("./src/components/public/Layout/index.vue")["default"];
    LayoutSelect: typeof import("./src/components/base/LayoutSelect/index.vue")["default"];
    Menu: typeof import("./src/components/base/Menu/index.vue")["default"];
    MenuItem: typeof import("./src/components/base/Menu/MenuItem.vue")["default"];
    MessageList: typeof import("./src/components/business/Home/MessageList/index.vue")["default"];
    MixedLineAndBar: typeof import("./src/components/business/Dashboard/dataReport/MixedLineAndBar/index.vue")["default"];
    MobilePhone: typeof import("./src/components/business/Login/MobilePhone/index.vue")["default"];
    NavigationPath: typeof import("./src/components/base/NavigationPath/index.vue")["default"];
    Options: typeof import("./src/components/business/Home/Options/index.vue")["default"];
    PageLayout: typeof import("./src/components/public/PageLayout/index.vue")["default"];
    Project: typeof import("./src/components/business/Dashboard/workbench/Project/index.vue")["default"];
    QrCodeLogin: typeof import("./src/components/business/Login/QrCodeLogin/index.vue")["default"];
    QuickNav: typeof import("./src/components/business/Dashboard/workbench/QuickNav/index.vue")["default"];
    RenderView: typeof import("./src/components/public/RenderView/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SalesProductPie: typeof import("./src/components/business/Dashboard/Analysis/SalesProductPie/index.vue")["default"];
    SayHello: typeof import("./src/components/business/Dashboard/workbench/SayHello/index.vue")["default"];
    SearchBar: typeof import("./src/components/public/SearchBar/index.vue")["default"];
    SearchContainer: typeof import("./src/components/base/AppSearch/SearchContainer.vue")["default"];
    SettingContent: typeof import("./src/components/business/Home/SettingContent/index.vue")["default"];
    SwitchLanguage: typeof import("./src/components/base/SwitchLanguage/index.vue")["default"];
    SwitchTheme: typeof import("./src/components/base/SwitchTheme/index.vue")["default"];
    Tabs: typeof import("./src/components/base/Tabs/index.vue")["default"];
    ThemeRiver: typeof import("./src/components/business/Dashboard/dataReport/ThemeRiver/index.vue")["default"];
    ThirdParty: typeof import("./src/components/business/Login/ThirdParty/index.vue")["default"];
    VisitAnalysis: typeof import("./src/components/business/Dashboard/Analysis/VisitAnalysis/index.vue")["default"];
    VisitAnalysisBar: typeof import("./src/components/business/Dashboard/Analysis/VisitAnalysisBar/index.vue")["default"];
    VisitRadar: typeof import("./src/components/business/Dashboard/Analysis/VisitRadar/index.vue")["default"];
    VisitSource: typeof import("./src/components/business/Dashboard/Analysis/VisitSource/index.vue")["default"];
    Watermark: typeof import("./src/components/public/Watermark/index.vue")["default"];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import("element-plus/es")["ElLoadingDirective"];
  }
}
