export default {
  Calibrate: ["admin"],
  AutomatedTool: ["admin"],
  PageDesigner: ["admin"],
  ProcessEngine: ["admin"],
  OnlineEditor: ["admin"],
  SingleFileComponent: ["admin"],
  dashboard: ["admin"],
  analysis: ["admin"],
  workbench: ["admin"],
  ExternalPage: ["admin"],
  elementPlusDoc: ["admin"],
  GrowAdminDoc: ["admin"],
  ComponentDocument: ["admin"],
  ElementListPage: ["admin"],
  ListPage: ["minor"],
  ElBaseList: ["minor"],
  ElVirtualList: ["minor"],
  VxeVirtualList: ["admin"],
  dataReport: ["admin"],
  boot: ["admin"],
  customPage: ["admin", "minor", "role"],
  customPage1: ["admin"],
  customPage2: ["admin"],
  Feat: ["admin"],
  DownExcel: ["admin"],
  OpenSubpage: ["admin"],
  MessagePrompt: ["admin"],
  SystemManagement: ["admin"],
  AccountManagement: ["admin"],
  RoleManagement: ["admin"],
  MenuManagement: ["admin"],
  CountToExample: ["admin"],
  SplitPaneTest: ["admin"],
  "customPage1-1": ["minor"],
  "customPage2-2": ["role"],
  OverflowList:["admin"],
};
