name: CD
on: 
  push: 
    branches: main
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Cache
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{runner.OS}}-${{hashFiles('**/yarn.lock')}}
      - name: Installing Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install
      - name: Building
        run: |
          yarn build
      - name: Update dist folder to repository
        env:
          REPO_USERNAME: "ZhQuella"
          DIST_REPO: "grow_admin"
          GITHUB_TOKEN: ${{ secrets.PROJECT_ACCESS_TOKEN }}
        run: |
          git config --global user.email "827265905@qq.com"
          git config --global user.name "ZhQuella"
          cd dist && git init && git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet "https://$GITHUB_TOKEN@github.com/$REPO_USERNAME/$DIST_REPO.git" 
          git push -u origin main