name: CD
on: 
  push: 
    branches: main
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: 
      - name: Use Node.js
        uses: 
        with:
          node-version: "16.x"
      - name: Installing Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install
      - name: Building
        run: |
          yarn build
      - name: Update dist folder to repository
        uses: 
        env:
          REPO_USERNAME: "ZhQuella"
          DIST_REPO: "grow_admin"
          GITHUB_TOKEN: ${{ secrets.PROJECT_ACCESS_TOKEN }}